"""
Methods to document a single ASTNode.

Author:
	Pim van Leeuwen (1303422, p.p.h.v.leeuwen@student.tue.nl)
"""

# needed for the LLM interface
import os
import warnings
import ollama
import requests
import uuid

from src.tree.tree_nodes import ASTNode, ASTNodeType
from src.llm.prompt import METHOD_PROMPT, SHORT_TASK, LONG_TASK, NO_CONTEXT_METHOD_PROMPT

# API URL and max retries variables
API_URL = "https://api.generative.engine.capgemini.com/v2/llm/invoke"
API_KEY = os.environ.get('CAPGEMINI_API_KEY')
MODEL_PROVIDER = os.environ.get('MODEL_PROVIDER')
MODEL_NAME = os.environ.get('MODEL_NAME')
PROVIDE_CODE = os.environ.get('PROVIDE_CODE')
USE_LOCAL_LLM = os.environ.get('USE_LOCAL_LLM')
PROVIDE_CONTEXT = os.environ.get('PROVIDE_CONTEXT')

MAX_RETRIES = 10

def invoke_llm_local(prompt, model="llama3.1"):
	"""calls the local LLM to generate LLM documentation

	Args:
		prompt (str): The prompt to parse.
		model (str, optional): The model to use. Defaults to "llama3.1".

	Returns:
		str: The response generated by the LLM.
	"""

	response = ollama.chat(model=model, options={"temperature":0}, messages=[
		{
			'role': 'user',
			'content': prompt,
		},
	])

	return response['message']['content']

def invoke_llm_api(prompt, prompt_id="123e4567-e89b-12d3-a456-426614174002"):
	# print("api")
	"""calls the API to generate LLM documentation

	Args:
		prompt (str): The prompt to parse.
		prompt_id (str, optional): UUID of the prompt. Defaults to "123e4567-e89b-12d3-a456-426614174002".

	Returns:
		str: The response generated by the llm.
	"""

	if not API_KEY: warnings.warn("No API Key found to document with")

	headers = {
		"x-api-key": API_KEY,
		"Content-Type": "application/json",
		"Accept": "application/json"
	}

	payload = {
		"action": "run",
		"modelInterface": "langchain",
		"data": {
			"mode": "chain",
			"text": prompt,
			"files": [],
			"modelName": MODEL_NAME,
			"provider": MODEL_PROVIDER,
			"systemPrompt": "You are an AI docs assistant. Your task is to generate clear, concise docs for the given code of an object to help developers and beginners understand its function and usage.",
			"sessionId": prompt_id,
			"modelKwargs": {
				"maxTokens": 512,
				"temperature": 0,
				"streaming": False,
				"topP": 0.9
			}
		}
	}

	for i in range(MAX_RETRIES):
		try:
			response = requests.post(API_URL, headers=headers, json=payload)
			if response.status_code == 200:
				return response.json().get("content")
			raise Exception(f"Not 200 return code, but {response.status_code}")
		except Exception as e:
			warnings.warn(f"try {i} failed with {e}")
	else:
		return None


def document_node(node: ASTNode):
	"""
	given a method node and the corresponding tree, query the LLM to generate docs and return the output

	Args:
		node (ASTNode): The node to document.
	"""

	# set the repo name
	long_prompt = LONG_TASK
	no_context_prompt = NO_CONTEXT_METHOD_PROMPT
	prompt = METHOD_PROMPT.replace("{project_structure_prefix}", node.get_path().split("/")[0])
	# set the path of the node
	prompt = prompt.replace("{file_path}", node.get_path())
	# set the name of the method/class
	prompt = prompt.replace("{name}", node.get_name())
	long_prompt = long_prompt.replace("{name}", node.get_name())
	# set the content of the code
	prompt = prompt.replace("{code_content}", node.get_content())
	no_context_prompt = no_context_prompt.replace("{code_content}", node.get_content())

	# set the type of the node
	# This will warn if we document an unsupported node
	match node.get_type():
		case ASTNodeType.METHOD:
			prompt = prompt.replace("{type}", "Method")
		case ASTNodeType.OBJECT:
			prompt = prompt.replace("{type}", "Class")
		case _ :
			warnings.warn("You are trying to document the following node: " + str(node))

	# fetch the parameters and add these
	param_list = node.get_parameters()

	param_prompt = ""
	if param_list:
		param_prompt += "**Parameters**:\\\n"
		for param in param_list:
			param_prompt += f"`{param}`: *FILL IN* \\\n"
	long_prompt = long_prompt.replace("{parameters_or_attribute}", param_prompt) if PROVIDE_CONTEXT == "True" else long_prompt.replace("{parameters_or_attribute}", "")

	# fetch the calls and add these
	call_list = node.get_calls()

	call_prompt = ""
	if call_list:
		call_prompt += "## Calls \n This code calls the following methods within the repository: \n"
		for call in call_list:
			# This should become the docs
			call_prompt += f"### {call.get_path()}.{call.name} \n"
			if call.has_documentation():
				call_prompt += f" - Explanation:  _{call.get_short_documentation()}_ \n"

	prompt = prompt.replace("{function_calls}", call_prompt)

	# fetch the calls and add these
	children = node.get_children()

	children_prompt = ""
	if children:
		children_prompt += "## Children \n This code contains the following methods/classes that are already documented: \n"
		for child in children:
			if child.has_documentation():
				children_prompt += f"### {child.name} \n"
				children_prompt += f"{child.get_short_documentation()} \n"
	prompt = prompt.replace("{children}", children_prompt)
	short_prompt = prompt + SHORT_TASK
	prompt = prompt + long_prompt if PROVIDE_CONTEXT == "True" else no_context_prompt + long_prompt

	# add the prompt so that we can inspect it later
	os.makedirs(os.path.dirname(f"prompts/{node.get_path()}/{node.get_name()}.md"), exist_ok=True)
	with open(f"prompts/{node.get_path()}/{node.get_name()}.md", "w") as f:
		f.write("# PROMPT")
		f.write(prompt)

	# PROMPTING THE LLM

	# set the short documentation in the node
	if PROVIDE_CONTEXT == "True":
		print("setting short")
		node_short_documentation = invoke_llm_local(short_prompt) if USE_LOCAL_LLM == "True" else invoke_llm_api(short_prompt, str(uuid.uuid4()))
		node.set_short_documentation(node_short_documentation)

	# set the documentation in the node
	node_documentation = invoke_llm_local(prompt) if USE_LOCAL_LLM == "True" else invoke_llm_api(prompt, str(uuid.uuid4()))
	if PROVIDE_CODE  == "True":
		# print("Writing Code")
		node_documentation += "\\\\\n## Code: \n```\n" + node.get_content() + "\n```"
	node.set_documentation(node_documentation)

	# write the comment to the docs
	os.makedirs(os.path.dirname(f"docs/{node.get_path()}/{node.get_name()}.md"), exist_ok=True)
	with open(f"docs/{node.get_path()}/{node.get_name()}.md", "w") as f:
		f.write(node.get_documentation())

	# This is for testing to export the short documentation
	# os.makedirs(os.path.dirname(f"docs/{node.get_path()}/{node.get_name()}_short.md"), exist_ok=True)
	# with open(f"docs/{node.get_path()}/{node.get_name()}_short.md", "w") as f:
	# 	f.write(node.get_short_documentation())
